CREATE DATABASE web_databse;

CREATE TABLE IF NOT EXISTS pesan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    nomor VARCHAR(20) NOT NULL,
    lokasi VARCHAR(255) NOT NULL,
    pesanan VARCHAR(20) NOT NULL,
    waktu_pesan TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
